using FluentAssertions;
using NUnit.Framework;
using OpenQA.Selenium;

namespace EVBoxSubmitForm
{
    class Tests
    {
        private IWebDriver _driver;
        private Utils _utils;

        [SetUp]
        public void Setup()
        {
            _driver = new DriverInit().GetDriver();
            _utils = new Utils(_driver);
            _utils.AcceptCookies();
            _utils.ChangeLanguageTo("English");
        }

        [Test]
        public void SuccesfullySendRequestHelpFormToSuport()
        {
            //Verify the start page is opened
            _utils.VerifyPageIsOpened("Electric vehicle charging solutions").Should().BeTrue();
            _utils.NavigateToPage("About", "Contact us");
            _utils.VerifyPageIsOpened("Contact us").Should().BeTrue();

            new ContactUsPageElements(_driver).ClickRequestForHelpButton();

            var supportPage = new SupportPageElements(_driver);
            supportPage.EnterFirstname("Mindaugas");
            supportPage.EnterLastname("L.");
            supportPage.EnterEmail("mindaugas.5xqxzeas@mailosaur.io");
            supportPage.FillInAddress("0000", "Amsterdam", "Netherlands");
            supportPage.EnterMessage("This is a test message generated by automated script.");
            supportPage.ClickSendButton();
            supportPage.VerifySuccessMessageIsShown("Thanks a million").Should().BeTrue();
        }

        [TearDown]
        public void TearDown()
        {
            _driver.Quit();
        }
    }
}
